name: CronJob

on:
  # schedule:
  #  - cron: "0 0 * * *" # Every day at 00:00

  workflow_dispatch:

permissions:
  contents: write

jobs:
  check_for_new_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Generate new emojis list
        id: generate
        run: |
          python scripts/generate_emojis_collection.py templates/emojis_collection_template.py discord_emojis/emojis_collection.py

          if [ "$(git status --short)" ]; then
            echo "should_release=true" >> $GITHUB_OUTPUT
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Create release
        if: steps.generate.outputs.should_release == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_SLUG: ${{ github.repository }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          bash scripts/create_release.sh
